apiVersion: v1
kind: Pod
metadata:
  labels:
    submitterName: piero
  name: piero-pod
spec:
  containers:
  - command:
    - /bin/bash
    args:
    - -c
    - "rm -rf /app ; ln -s /scratch/personal/piero/REPO /app ; while true; do sleep 30; done;"
    env:
    - name: DANCER_APPDIR
      value: /app
    - name: DANCER_ENVIRONMENT
      value: production
    - name: FARM_NAME
      value: kubernetes
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          key: clus_DB_HOST
          name: db-config
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          key: clus_DB_NAME
          name: db-config
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: clus_DB_PASSWORD
          name: db-config
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          key: clus_DB_PORT
          name: db-config
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          key: clus_DB_USER
          name: db-config
    - name: URL
      valueFrom:
        configMapKeyRef:
          key: URL
          name: JR-general-config
    - name: SERVICE_TOKEN
      valueFrom:
        secretKeyRef:
          key: SERVICE_TOKEN
          name: JR-token
    image: IMAGE:TAG
    imagePullPolicy: IfNotPresent
    name: piero-pod
    resources:
      limits:
        cpu: "2"
        memory: 12Gi
      requests:
        cpu: "2"
        memory: 12Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: ref-data
    - mountPath: /scratch
      name: scratch
    - mountPath: /data/pipeline-ns/pipeline/output
      name: pipeline-output-pvc-map
    - mountPath: /data/pipeline-ns/pipeline/source
      name: pipeline-source-pvc-map
    workingDir: /scratch
  dnsPolicy: ClusterFirst
  nodeSelector:
    farmNode: "true"
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  volumes:
  - name: ref-data
    persistentVolumeClaim:
      claimName: pipeline-ref-pvc
  - name: scratch
    persistentVolumeClaim:
      claimName: pipeline-scratch-pvc
  - name: pipeline-output-pvc-map
    persistentVolumeClaim:
      claimName: pipeline-output-pvc
  - name: pipeline-source-pvc-map
    persistentVolumeClaim:
      claimName: pipeline-source-pvc
